#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'git'
cookbook 'openssl'
cookbook 'postgresql'
cookbook 'python'
cookbook 'zlib'
cookbook 'erlang'
cookbook 'rabbitmq'
cookbook 'nginx'
cookbook 'runit'
cookbook 'chef-cookbook-python-psycopg2',
    :git => 'git@github.com:rileycrane/chef-cookbook-python-psycopg2.git'
cookbook 'chef-cookbook-libjpeg',
    :git => 'git://github.com/jbergantine/chef-cookbook-libjpeg.git'
cookbook 'chef-cookbook-libfreetype',
    :git => 'git://github.com/jbergantine/chef-cookbook-libfreetype.git'
cookbook 'redis',
	:git => 'https://github.com/ctrabold/chef-redis.git'
